#!/bin/bash
set -e

# A UUID to identify that this script has touched a .vimrc
MY_UUID="fa0e8780-9acb-479f-a68a-b059277ff70b"

# All Vim stuff goes in the directory this script is in
VIMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Make sure there's a directory for external stuff
mkdir -p $VIMDIR/ext

# Make sure there's a tmp directory for stuff like viminfo
mkdir -p $VIMDIR/tmp

# Make sure it has the subdirectories referenced in src/paths.vim
mkdir -p $VIMDIR/tmp/backup
mkdir -p $VIMDIR/tmp/swap
mkdir -p $VIMDIR/tmp/undo

# Make sure there's a .vimrc
if ! [ -e ~/.vimrc ] ; then
    touch ~/.vimrc
fi

# Modify the .vimrc, but only if it's the first time
# i.e. if the UUID isn't already there
if ! grep -q $MY_UUID ~/.vimrc ; then
    # In case the .vimrc doesn't already end with a newline
    echo ""                                                                 >> ~/.vimrc

    # So someone reading the .vimrc knows what they're looking at
    echo "\" Jeremy's Vim Configurations"                                   >> ~/.vimrc

    # So that if this script is run again by mistake, we don't modify the
    # .vimrc again
    echo "\" $MY_UUID"                                                      >> ~/.vimrc

    # Default value of g:jeremyColouredColumns
    echo "let g:jeremyColouredColumns=\"81,82\""                            >> ~/.vimrc

    # Default value of g:jeremyColouredColumnFiletypes
    echo "let g:jeremyColouredColumnFileTypes=\"vim,h,c,cpp,python,sh,go\"" >> ~/.vimrc

    # A place to put extra plugins specific to this environment
    echo "let g:jeremyExtraPlugins=[]"                                      >> ~/.vimrc

    # Vim will run src/main.vim on startup
    echo "source $VIMDIR/src/main.vim"                                      >> ~/.vimrc
fi
